---
title: "cross_validation"
author: "Angelica Bailey"
date: "2025-11-11"
output: github_document
---

```{r}
library(tidyverse)
library(modelr)
library(mgcv)
```


```{r}
library(p8105.datasets)
library(modelr)
set.seed(1)
```


Load the LIDAR
```{r}
data("lidar")
```


Look at the data
```{r}
lidar_df =
  lidar |> 
  mutate(id = row_number())

lidar_df |> 
  ggplot(aes(x = range, y = logratio)) +
  geom_point()
#non-constant variance in plot, is my model complex enough or is too much?
```


## Create dataframes
```{r}
#keeping 80% of dataset in train _df
train_df = sample_frac(lidar_df, size = .8) |> 
  arrange(id)

#rows that are in lidar_df that did not show up in test_df
test_df = anti_join(lidar_df, train_df, by = "id")
```

Look at these
```{r}
ggplot(train_df, aes(x = range, y = logratio)) +
  geom_point() +
  geom_point(data = test_df, color = "red")
```


Fit a few models to the train_df

```{r}
linear_mod = lm(logratio ~ range, data = train_df)
smooth_mod = mgcv::gam(logratio ~ s(range), data = train_df)
wiggly_mod = mgcv::gam(logratio ~ s(range, k = 30), sp = 10e-6, data = train_df) 
#wiggly makes slightly worse predictions than smooth, it is overfitting & not super generalizeable
```


Look at this
```{r}
train_df |> 
  add_predictions(wiggly_mod) |> 
  ggplot(aes(x = range, y = logratio)) +
  geom_point() +
  geom_line(aes(y = pred), color = "red")
#not enough complexity in line, not a good fit for making predictions
```

Try computing our RMSEs
```{r}
rmse(linear_mod, test_df)
rmse(smooth_mod, test_df)
rmse(wiggly_mod, test_df)
```


## Let's iterate
```{r}
cv_df =
  crossv_mc(lidar_df, n = 100) |> 
  mutate(
    train = map(train, as_tibble),
    test = map(test, as_tibble)
  )
```


Did this work?
```{r}
#giving training-testing split, doing 80/20 over and over again
cv_df |> pull(train) |> nth(2)

```


Lets fit models over and over

```{r}
#take first testing dataset and fit linear model
cv_df = cv_df |> 
  mutate(
    linear_fits = map(train, \(df) lm(logratio ~ range, data = df)),
    smooth_fits = map(train, \(df) mgcv::gam(logratio ~ s(range), data = df)),
    wiggly_fits = map(train, \(df) mgcv::gam(logratio ~ s(range, k = 50), sp = 10e-8, data = df))
    ) |> 
  mutate(
    rmse_linear = map2_dbl(linear_fits, test, rmse),
    rmse_smooth = map2_dbl(smooth_fits, test, rmse),
    rmse_wiggly = map2_dbl(wiggly_fits, test, rmse)
  )


#in general, wiggly fit is doing better
#doing training-testing split 100 times than fitting them and computing rmse
  
```


Lets try to look at this better
```{r}
cv_df |> 
  select(starts_with("rmse")) |> 
  pivot_longer(
    everything(),
    names_to = "model",
    values_to = "rmse",
    names_prefix = "rmse_"
  ) |> 
  ggplot(aes(x = model, y = rmse)) +
  geom_violin()

#smooth model doing the best, wiggle model too complex, linear model doing the worst
```



## Child growth

```{r}
growth_df =
  read_csv("data/nepalese_children.csv")
```
Weight v arm_c
```{r}
growth_df |> 
  ggplot(aes(x = weight, y = armc)) +
  geom_point(alpha = .5)
```


Lets show the models we might use.
```{r}
#piecewise linear function
growth_df =
  growth_df |> 
  mutate(
    weight_cp7 = (weight > 7) * (weight - 7)
  )
```


Lets fit three models
```{r}
linear_mod = lm(armc ~ weight, data = growth_df)
pwl_mod = lm(armc ~ weight + weight_cp7, data = growth_df)
smooth_mod = mgcv::gam(armc ~ s(weight), data = growth_df) #more plausible than the sharp change in pwl, but can only interpret by looking at it
```

```{r}
growth_df |> 
  add_predictions(smooth_mod) |> 
  ggplot(aes(x = weight, y = armc)) +
  geom_point(alpha = .5) +
  geom_line(aes(y = pred), color = "red")
```

Now cross validate
```{r}
cv_df =
  crossv_mc(growth_df, n = 100) |> 
  mutate(
    train = map(train, as_tibble),
    test = map(test, as_tibble)
  )


```


```{r}
cv_df =
  cv_df |> 
  mutate(
    linear_mod = map(train, \(df) lm(armc ~ weight, data = df)),
    pwl_mod = map(train, \(df) lm(armc ~ weight + weight_cp7, data = df)),
    smooth_mod = map(train, \(df) mgcv::gam(armc ~ weight, data = df))
  ) |> 
  mutate(
    rmse_linear = map2_dbl(linear_mod, test, rmse),
    rmse_pwl = map2_dbl(pwl_mod, test, rmse),
    rmse_smooth = map2_dbl(smooth_mod, test, rmse)
  )

```


```{r}
cv_df |> 
  select(starts_with("rmse")) |> 
  pivot_longer(
    everything(),
    names_to = "model",
    values_to = "rmse",
    names_prefix = "rmse_"
  ) |> 
  ggplot(aes(x = model, y = rmse)) +
  geom_violin()

```






